apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcamp-back
  namespace: devcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcamp-back
  template:
    metadata:
      labels:
        app: devcamp-back
    spec:
      containers:
        - name: devcamp-back
          image: gucasassi/devcamp-back:1.4.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: devcamp-back-config
                  key: app_port

            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: devcamp-back-secret
                  key: mongodb_uri

            - name: GEOCODER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devcamp-back-secret
                  key: geocoder_api_key

            - name: GEOCODER_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: devcamp-back-secret
                  key: geocoder_provider

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devcamp-back-secret
                  key: jwt_secret

            - name: JWT_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: devcamp-back-config
                  key: jwt_expire

            - name: JWT_COOKIE_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: devcamp-back-config
                  key: jwt_cookie_expire

            - name: MAX_FILE_UPLOAD
              valueFrom:
                configMapKeyRef:
                  name: devcamp-back-config
                  key: max_file_upload

            - name: FILE_UPLOAD_PATH
              valueFrom:
                configMapKeyRef:
                  name: devcamp-back-config
                  key: file_upload_path

            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: devcamp-back-secret
                  key: smtp_host

            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: devcamp-back-secret
                  key: smtp_port

            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: devcamp-back-secret
                  key: smtp_user

            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devcamp-back-secret
                  key: smtp_password

            - name: FROM_NAME
              valueFrom:
                configMapKeyRef:
                  name: devcamp-back-config
                  key: from_name

            - name: FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: devcamp-back-config
                  key: from_email
